location = "japaneast"
default_user = "<DEFAULT USER NAME>"
default_password = "<USER PASSWORD>"
subscription_id = "<SUBSCRIPTION ID>"
client_id = "<CLIENT ID>"
client_secret = "<CLIENT SECRET>"
tenant_id = "<TENANT ID>"